export const roxanne = {
  id: "l34kj53lk5j35l3jk",
  title: "Roxanne",
  artist: "The Police",
  year: "1978",
  studio: "Surrey Sound Studios",
  location: "Leatherhead, Surrey, U.K.",
  slug: "roxanne",
  bpm: 92,
  start: 1,
  end: 180,
  tracks: [
    {
      id: crypto.randomUUID(),
      name: "Drums",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Drums.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      trackPanelPosition: { x: 0, y: 0 },
      trackPanelSize: { width: "325px", height: "auto" },
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
      delaysBypass: [false, false],
      pitchShiftsBypass: [false, false],
      pitchShiftsMix: [0.5, 0.5],
      pitchShiftsPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Bass",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Bass.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      trackPanelPosition: { x: 0, y: 0 },
      trackPanelSize: { width: "325px", height: "auto" },
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
      delaysBypass: [false, false],
      pitchShiftsBypass: [false, false],
      pitchShiftsMix: [0.5, 0.5],
      pitchShiftsPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Guitar",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Guitar.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      trackPanelPosition: { x: 0, y: 0 },
      trackPanelSize: { width: "325px", height: "auto" },
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
      delaysBypass: [false, false],
      pitchShiftsBypass: [false, false],
      pitchShiftsMix: [0.5, 0.5],
      pitchShiftsPitch: [5, 5],
    },
    {
      id: crypto.randomUUID(),
      name: "Vocals",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/roxanne/Roxanne_Vocal.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      fxName: ["nofx", "nofx"],
      sends: [false, false],
      trackPanelPosition: { x: 0, y: 0 },
      trackPanelSize: { width: "325px", height: "auto" },
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
      delaysBypass: [false, false],
      pitchShiftsBypass: [false, false],
      pitchShiftsMix: [0.5, 0.5],
      pitchShiftsPitch: [5, 5],
    },
  ],
};
